<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="URF.Core.Services" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modules.Shipping.Data\Modules.Accounting.Data.csproj" />
    <ProjectReference Include="..\Modules.Shipping.Entities\Modules.Accounting.Entities.csproj" />
    <ProjectReference Include="..\Modules\Orders\Modules.Orders.Data\Modules.Orders.Data.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Modules.Catalog.Data\Modules.Catalog.Data.csproj" />
    <ProjectReference Include="..\Modules\Catalog\Modules.Catalog.Entities\Modules.Catalog.Entities.csproj" />
    <ProjectReference Include="..\App.Data\App.Shared.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Solf">
      <HintPath>..\Solf\Solf.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
