//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Answer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Answer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("app.Resources._Answer", typeof(_Answer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is not clear: Doctor name is not clear.
        /// </summary>
        public static string DoctorNameNotClear {
            get {
                return ResourceManager.GetString("DoctorNameNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is not clear: Doctor stamp is not clear.
        /// </summary>
        public static string DoctorStampNotClear {
            get {
                return ResourceManager.GetString("DoctorStampNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old prescription: Must be submitted in 6 days after it is prescribed.
        /// </summary>
        public static string OldPrescriptionDate {
            get {
                return ResourceManager.GetString("OldPrescriptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is not clear: Patient name is not clear.
        /// </summary>
        public static string PatientNameNotClear {
            get {
                return ResourceManager.GetString("PatientNameNotClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo is not clear: Prescription date is not clear.
        /// </summary>
        public static string PrescriptionDateNotClear {
            get {
                return ResourceManager.GetString("PrescriptionDateNotClear", resourceCulture);
            }
        }
    }
}
