//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wien.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wien.Resources._NotificationMessages", typeof(_NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is in need of an urgent help.
        /// </summary>
        public static string HelpRequestText {
            get {
                return ResourceManager.GetString("HelpRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent Help Needed !.
        /// </summary>
        public static string HelpRequestTitle {
            get {
                return ResourceManager.GetString("HelpRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has read the project pdf &apos;{1}&apos;.
        /// </summary>
        public static string MarkAsReadText {
            get {
                return ResourceManager.GetString("MarkAsReadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project pdf is read.
        /// </summary>
        public static string MarkAsReadTitle {
            get {
                return ResourceManager.GetString("MarkAsReadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding {0}.
        /// </summary>
        public static string MarkedHimselfAsText {
            get {
                return ResourceManager.GetString("MarkedHimselfAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} marked himself as ({1}).
        /// </summary>
        public static string MarkedHimselfAsTitle {
            get {
                return ResourceManager.GetString("MarkedHimselfAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has added a live report..
        /// </summary>
        public static string UserAddedLiveReportText {
            get {
                return ResourceManager.GetString("UserAddedLiveReportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New live report.
        /// </summary>
        public static string UserAddedLiveReportTitle {
            get {
                return ResourceManager.GetString("UserAddedLiveReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has started recording his live track.
        /// </summary>
        public static string UserAddedLiveTrackText {
            get {
                return ResourceManager.GetString("UserAddedLiveTrackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New live track.
        /// </summary>
        public static string UserAddedLiveTrackTitle {
            get {
                return ResourceManager.GetString("UserAddedLiveTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has moved from {1} to {2}.
        /// </summary>
        public static string UserChangedCityText {
            get {
                return ResourceManager.GetString("UserChangedCityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User city changed.
        /// </summary>
        public static string UserChangedCityTitle {
            get {
                return ResourceManager.GetString("UserChangedCityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has added logged in for the first time.
        /// </summary>
        public static string UserLoggedInForTheFirstTimeText {
            get {
                return ResourceManager.GetString("UserLoggedInForTheFirstTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Login Notification.
        /// </summary>
        public static string UserLoggedInForTheFirstTimeTitle {
            get {
                return ResourceManager.GetString("UserLoggedInForTheFirstTimeTitle", resourceCulture);
            }
        }
    }
}
