//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("app.Resources._Settings", typeof(_Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About (ar).
        /// </summary>
        public static string About_ar {
            get {
                return ResourceManager.GetString("About_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About (en).
        /// </summary>
        public static string About_en {
            get {
                return ResourceManager.GetString("About_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About (tr).
        /// </summary>
        public static string About_tr {
            get {
                return ResourceManager.GetString("About_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Note.
        /// </summary>
        public static string FooterNote {
            get {
                return ResourceManager.GetString("FooterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy (ar).
        /// </summary>
        public static string PrivacyPolicy_ar {
            get {
                return ResourceManager.GetString("PrivacyPolicy_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy (en).
        /// </summary>
        public static string PrivacyPolicy_en {
            get {
                return ResourceManager.GetString("PrivacyPolicy_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy (tr).
        /// </summary>
        public static string PrivacyPolicy_tr {
            get {
                return ResourceManager.GetString("PrivacyPolicy_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions (ar).
        /// </summary>
        public static string TermsAndConditions_ar {
            get {
                return ResourceManager.GetString("TermsAndConditions_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions (en).
        /// </summary>
        public static string TermsAndConditions_en {
            get {
                return ResourceManager.GetString("TermsAndConditions_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms And Conditions (tr).
        /// </summary>
        public static string TermsAndConditions_tr {
            get {
                return ResourceManager.GetString("TermsAndConditions_tr", resourceCulture);
            }
        }
    }
}
