<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="5.0.6" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="5.0.6" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="URF.Core.All" Version="3.0.0" />
    <PackageReference Include="URF.Core.EF" Version="5.0.0" />
    <PackageReference Include="URF.Core.EF.Trackable" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Solf">
      <HintPath>..\Solf\Solf.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\_Committee.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Committee.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_JoinStatus.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_JoinStatus.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_City.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_City.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_InitiativeType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_InitiativeType.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_AppRole.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_AppRole.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_AppRoleName.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_AppRoleName.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_AppUser.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_AppUser.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Category.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Category.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Contact.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Contact.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Content.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Content.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_DaysOfWeek.ar.Designer.cs">
      <DependentUpon>_DaysOfWeek.ar.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <Compile Update="Resources\_Entities.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Entities.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Errors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Errors.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Event.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Event.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Faq.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Faq.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Coupon.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Coupon.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_PermissionKey.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_PermissionKey.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Gender.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Gender.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Location.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Location.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Notification.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Notification.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_SmsLog.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_SmsLog.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_StoreItem.ar.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_StoreItem.ar.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_SyncTask.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_SyncTask.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Tag.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Tag.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\JoinStatus.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_JoinStatus.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_JoinStatus.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_City.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_City.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_City.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Committee.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Committee.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Committee.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Event.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_InitiativeType.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_InitiativeType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_InitiativeType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppRoleName.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppUser.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Category.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Category.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Category.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Category.tr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Contact.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Contact.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Contact.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Content.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Content.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Content.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_DaysOfWeek.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_DaysOfWeek.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_DaysOfWeek.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Entities.ar.resx">
      <LastGenOutput>_Entities.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Entities.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Entities.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Errors.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Event.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Event.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Faq.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Faq.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Faq.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Coupon.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Coupon.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Coupon.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_PermissionKey.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_PermissionKey.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Gender.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Gender.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Gender.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Location.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Location.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppRole.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_AppRole.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppRoleName.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_AppRoleName.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Clinic.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppUser.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_AppUser.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Errors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Errors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Notification.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Notification.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_SmsLog.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_SmsLog.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_SyncTask.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_SyncTask.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Tag.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Tag.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
