<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="6.0.6" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="6.0.6" />
    <PackageReference Include="URF.Core.EF.Trackable" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Solf">
      <HintPath>..\Solf\Solf.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\_AppRole.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_AppRole.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_AppRoleName.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_AppRoleName.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_AppUser.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_AppUser.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Banner.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Banner.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_City.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_City.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Content.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Content.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Entities.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Entities.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Errors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Errors.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Faq.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Faq.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Gender.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Gender.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Notification.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Notification.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Order.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Order.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_OrderStatus.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_OrderStatus.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_PaymentMethod.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_PaymentMethod.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_PaymentStatus.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_PaymentStatus.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_PermissionKey.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_PermissionKey.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Product.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Product.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_RequestStatus.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_RequestStatus.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Review.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Review.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_SmsLog.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_SmsLog.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_SyncTask.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_SyncTask.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Tag.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Tag.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\_AppRole.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_AppRole.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppRoleName.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppRoleName.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_AppRoleName.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_AppUser.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_AppUser.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Banner.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Banner.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Banner.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_City.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_City.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_City.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Content.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Content.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Content.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Entities.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Entities.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Entities.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Errors.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Errors.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Errors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Faq.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Faq.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Faq.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Gender.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Gender.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Notification.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Notification.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Order.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Order.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_OrderStatus.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_OrderStatus.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_OrderStatus.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_PaymentMethod.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_PaymentMethod.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_PaymentMethod.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_PaymentStatus.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_PaymentStatus.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_PermissionKey.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_PermissionKey.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_PermissionKey.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Product.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Product.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_RequestStatus.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_RequestStatus.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_RequestStatus.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Review.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Review.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_SmsLog.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_SmsLog.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_SyncTask.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_SyncTask.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Tag.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>_Tag.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
