using System.Text.RegularExpressions;
using System.Web;

namespace App.Shared.Services.Extentions
{
    public static class StringExtensions
    {
        public static string Truncate(this string value, int maxLength)
        {
            if (string.IsNullOrEmpty(value)) return value;
            return value.Length <= maxLength ? value : value.Substring(0, maxLength);
        }
        public static string ToSlug(this string text)
        {

            return text?.Trim()
                        .Replace("   ", "  ")
                        .Replace("  ", " ")
                        .Replace('\t', ' ')
                        .Replace(' ', '-')
                        .Replace('ª', 'a')
                        .Replace('º', 'o')
                        .Replace('À', 'A')
                        .Replace('Á', 'A')
                        .Replace('Â', 'A')
                        .Replace('Ã', 'A')
                        .Replace('Ä', 'A')
                        .Replace('Å', 'A')
                        .Replace("Æ", "AE")
                        .Replace('Ç', 'C')
                        .Replace('È', 'E')
                        .Replace('É', 'E')
                        .Replace('Ê', 'E')
                        .Replace('Ë', 'E')
                        .Replace('Ì', 'I')
                        .Replace('Í', 'I')
                        .Replace('Î', 'I')
                        .Replace('Ï', 'I')
                        .Replace('Ð', 'D')
                        .Replace('Ñ', 'N')
                        .Replace('Ò', 'O')
                        .Replace('Ó', 'O')
                        .Replace('Ô', 'O')
                        .Replace('Õ', 'O')
                        .Replace('Ö', 'O')
                        .Replace('Ù', 'U')
                        .Replace('Ú', 'U')
                        .Replace('Û', 'U')
                        .Replace('Ü', 'U')
                        .Replace('Ý', 'Y')
                        .Replace("Þ", "TH")
                        .Replace('ß', 's')
                        .Replace('à', 'a')
                        .Replace('á', 'a')
                        .Replace('â', 'a')
                        .Replace('ã', 'a')
                        .Replace('ä', 'a')
                        .Replace('å', 'a')
                        .Replace("æ", "ae")
                        .Replace('ç', 'c')
                        .Replace('è', 'e')
                        .Replace('é', 'e')
                        .Replace('ê', 'e')
                        .Replace('ë', 'e')
                        .Replace('ì', 'i')
                        .Replace('í', 'i')
                        .Replace('î', 'i')
                        .Replace('ï', 'i')
                        .Replace('ð', 'd')
                        .Replace('ñ', 'n')
                        .Replace('ò', 'o')
                        .Replace('ó', 'o')
                        .Replace('ô', 'o')
                        .Replace('õ', 'o')
                        .Replace('ö', 'o')
                        .Replace('ø', 'o')
                        .Replace('ù', 'u')
                        .Replace('ú', 'u')
                        .Replace('û', 'u')
                        .Replace('ü', 'u')
                        .Replace('ý', 'y')
                        .Replace("þ", "th")
                        .Replace('ÿ', 'y')
                        .Replace('Ø', 'O')
                        // Decompositions for Latin Extended-A)
                        .Replace('Ā', 'A')
                        .Replace('ā', 'a')
                        .Replace('Ă', 'A')
                        .Replace('ă', 'a')
                        .Replace('Ą', 'A')
                        .Replace('ą', 'a')
                        .Replace('Ć', 'C')
                        .Replace('ć', 'c')
                        .Replace('Ĉ', 'C')
                        .Replace('ĉ', 'c')
                        .Replace('Ċ', 'C')
                        .Replace('ċ', 'c')
                        .Replace('Č', 'C')
                        .Replace('č', 'c')
                        .Replace('Ď', 'D')
                        .Replace('ď', 'd')
                        .Replace('Đ', 'D')
                        .Replace('đ', 'd')
                        .Replace('Ē', 'E')
                        .Replace('ē', 'e')
                        .Replace('Ĕ', 'E')
                        .Replace('ĕ', 'e')
                        .Replace('Ė', 'E')
                        .Replace('ė', 'e')
                        .Replace('Ę', 'E')
                        .Replace('ę', 'e')
                        .Replace('Ě', 'E')
                        .Replace('ě', 'e')
                        .Replace('Ĝ', 'G')
                        .Replace('ĝ', 'g')
                        .Replace('Ğ', 'G')
                        .Replace('ğ', 'g')
                        .Replace('Ġ', 'G')
                        .Replace('ġ', 'g')
                        .Replace('Ģ', 'G')
                        .Replace('ģ', 'g')
                        .Replace('Ĥ', 'H')
                        .Replace('ĥ', 'h')
                        .Replace('Ħ', 'H')
                        .Replace('ħ', 'h')
                        .Replace('Ĩ', 'I')
                        .Replace('ĩ', 'i')
                        .Replace('Ī', 'I')
                        .Replace('ī', 'i')
                        .Replace('Ĭ', 'I')
                        .Replace('ĭ', 'i')
                        .Replace('Į', 'I')
                        .Replace('į', 'i')
                        .Replace('İ', 'I')
                        .Replace('ı', 'i')
                        .Replace("Ĳ", "IJ")
                        .Replace("ĳ", "ij")
                        .Replace('Ĵ', 'J')
                        .Replace('ĵ', 'j')
                        .Replace('Ķ', 'K')
                        .Replace('ķ', 'k')
                        .Replace('ĸ', 'k')
                        .Replace('Ĺ', 'L')
                        .Replace('ĺ', 'l')
                        .Replace('Ļ', 'L')
                        .Replace('ļ', 'l')
                        .Replace('Ľ', 'L')
                        .Replace('ľ', 'l')
                        .Replace('Ŀ', 'L')
                        .Replace('ŀ', 'l')
                        .Replace('Ł', 'L')
                        .Replace('ł', 'l')
                        .Replace('Ń', 'N')
                        .Replace('ń', 'n')
                        .Replace('Ņ', 'N')
                        .Replace('ņ', 'n')
                        .Replace('Ň', 'N')
                        .Replace('ň', 'n')
                        .Replace('ŉ', 'n')
                        .Replace('Ŋ', 'N')
                        .Replace('ŋ', 'n')
                        .Replace('Ō', 'O')
                        .Replace('ō', 'o')
                        .Replace('Ŏ', 'O')
                        .Replace('ŏ', 'o')
                        .Replace('Ő', 'O')
                        .Replace('ő', 'o')
                        .Replace("Œ", "OE")
                        .Replace("œ", "oe")
                        .Replace('Ŕ', 'R')
                        .Replace('ŕ', 'r')
                        .Replace('Ŗ', 'R')
                        .Replace('ŗ', 'r')
                        .Replace('Ř', 'R')
                        .Replace('ř', 'r')
                        .Replace('Ś', 'S')
                        .Replace('ś', 's')
                        .Replace('Ŝ', 'S')
                        .Replace('ŝ', 's')
                        .Replace('Ş', 'S')
                        .Replace('ş', 's')
                        .Replace('Š', 'S')
                        .Replace('š', 's')
                        .Replace('Ţ', 'T')
                        .Replace('ţ', 't')
                        .Replace('Ť', 'T')
                        .Replace('ť', 't')
                        .Replace('Ŧ', 'T')
                        .Replace('ŧ', 't')
                        .Replace('Ũ', 'U')
                        .Replace('ũ', 'u')
                        .Replace('Ū', 'U')
                        .Replace('ū', 'u')
                        .Replace('Ŭ', 'U')
                        .Replace('ŭ', 'u')
                        .Replace('Ů', 'U')
                        .Replace('ů', 'u')
                        .Replace('Ű', 'U')
                        .Replace('ű', 'u')
                        .Replace('Ų', 'U')
                        .Replace('ų', 'u')
                        .Replace('Ŵ', 'W')
                        .Replace('ŵ', 'w')
                        .Replace('Ŷ', 'Y')
                        .Replace('ŷ', 'y')
                        .Replace('Ÿ', 'Y')
                        .Replace('Ź', 'Z')
                        .Replace('ź', 'z')
                        .Replace('Ż', 'Z')
                        .Replace('ż', 'z')
                        .Replace('Ž', 'Z')
                        .Replace('ž', 'z')
                        .Replace('ſ', 's')
                        // Decompositions for Latin Extended-B)
                        .Replace('Ș', 'S')
                        .Replace('ș', 's')
                        .Replace('Ț', 'T')
                        .Replace('ț', 't')
                        // Euro Sign)
                        .Replace('€', 'E')
                        // GBP (Pound) Sign)
                        .Replace("£", "")
                        // Vowels with diacritic (Vietnamese))
                        // unmarked)
                        .Replace('Ơ', 'O')
                        .Replace('ơ', 'o')
                        .Replace('Ư', 'U')
                        .Replace('ư', 'u')
                        // grave accent)
                        .Replace('Ầ', 'A')
                        .Replace('ầ', 'a')
                        .Replace('Ằ', 'A')
                        .Replace('ằ', 'a')
                        .Replace('Ề', 'E')
                        .Replace('ề', 'e')
                        .Replace('Ồ', 'O')
                        .Replace('ồ', 'o')
                        .Replace('Ờ', 'O')
                        .Replace('ờ', 'o')
                        .Replace('Ừ', 'U')
                        .Replace('ừ', 'u')
                        .Replace('Ỳ', 'Y')
                        .Replace('ỳ', 'y')
                        // hook)
                        .Replace('Ả', 'A')
                        .Replace('ả', 'a')
                        .Replace('Ẩ', 'A')
                        .Replace('ẩ', 'a')
                        .Replace('Ẳ', 'A')
                        .Replace('ẳ', 'a')
                        .Replace('Ẻ', 'E')
                        .Replace('ẻ', 'e')
                        .Replace('Ể', 'E')
                        .Replace('ể', 'e')
                        .Replace('Ỉ', 'I')
                        .Replace('ỉ', 'i')
                        .Replace('Ỏ', 'O')
                        .Replace('ỏ', 'o')
                        .Replace('Ổ', 'O')
                        .Replace('ổ', 'o')
                        .Replace('Ở', 'O')
                        .Replace('ở', 'o')
                        .Replace('Ủ', 'U')
                        .Replace('ủ', 'u')
                        .Replace('Ử', 'U')
                        .Replace('ử', 'u')
                        .Replace('Ỷ', 'Y')
                        .Replace('ỷ', 'y')
                        // tilde)
                        .Replace('Ẫ', 'A')
                        .Replace('ẫ', 'a')
                        .Replace('Ẵ', 'A')
                        .Replace('ẵ', 'a')
                        .Replace('Ẽ', 'E')
                        .Replace('ẽ', 'e')
                        .Replace('Ễ', 'E')
                        .Replace('ễ', 'e')
                        .Replace('Ỗ', 'O')
                        .Replace('ỗ', 'o')
                        .Replace('Ỡ', 'O')
                        .Replace('ỡ', 'o')
                        .Replace('Ữ', 'U')
                        .Replace('ữ', 'u')
                        .Replace('Ỹ', 'Y')
                        .Replace('ỹ', 'y')
                        // acute accent)
                        .Replace('Ấ', 'A')
                        .Replace('ấ', 'a')
                        .Replace('Ắ', 'A')
                        .Replace('ắ', 'a')
                        .Replace('Ế', 'E')
                        .Replace('ế', 'e')
                        .Replace('Ố', 'O')
                        .Replace('ố', 'o')
                        .Replace('Ớ', 'O')
                        .Replace('ớ', 'o')
                        .Replace('Ứ', 'U')
                        .Replace('ứ', 'u')
                        // dot below)
                        .Replace('Ạ', 'A')
                        .Replace('ạ', 'a')
                        .Replace('Ậ', 'A')
                        .Replace('ậ', 'a')
                        .Replace('Ặ', 'A')
                        .Replace('ặ', 'a')
                        .Replace('Ẹ', 'E')
                        .Replace('ẹ', 'e')
                        .Replace('Ệ', 'E')
                        .Replace('ệ', 'e')
                        .Replace('Ị', 'I')
                        .Replace('ị', 'i')
                        .Replace('Ọ', 'O')
                        .Replace('ọ', 'o')
                        .Replace('Ộ', 'O')
                        .Replace('ộ', 'o')
                        .Replace('Ợ', 'O')
                        .Replace('ợ', 'o')
                        .Replace('Ụ', 'U')
                        .Replace('ụ', 'u')
                        .Replace('Ự', 'U')
                        .Replace('ự', 'u')
                        .Replace('Ỵ', 'Y')
                        .Replace('ỵ', 'y')
                        // Vowels with diacritic (Chinese Hanyu Pinyin))
                        .Replace('ɑ', 'a')
                        // macron)
                        .Replace('Ǖ', 'U')
                        .Replace('ǖ', 'u')
                        // acute accent)
                        .Replace('Ǘ', 'U')
                        .Replace('ǘ', 'u')
                        // caron)
                        .Replace('Ǎ', 'A')
                        .Replace('ǎ', 'a')
                        .Replace('Ǐ', 'I')
                        .Replace('ǐ', 'i')
                        .Replace('Ǒ', 'O')
                        .Replace('ǒ', 'o')
                        .Replace('Ǔ', 'U')
                        .Replace('ǔ', 'u')
                        .Replace('Ǚ', 'U')
                        .Replace('ǚ', 'u')
                        // grave accent)
                        .Replace('Ǜ', 'U')
                        .Replace('ǜ', 'u');
        }
        public static string Normalize(this string text)
        {

            return text?.Trim()?.ToLower()
                              ?.Replace("\t", " ")
                              ?.Replace("   ", " ")
                              ?.Replace("  ", " ")
                              ?.Replace("َ", "")
                              ?.Replace("ً", "")
                              ?.Replace("ُ", "")
                              ?.Replace("ٌ", "")
                              ?.Replace("ِ", "")
                              ?.Replace("ٍ", "")
                              ?.Replace("ّ", "")
                              ?.Replace("ـ", "")
                              ?.Replace('إ', 'ا')
                              ?.Replace('أ', 'ا')
                              ?.Replace('آ', 'ا')
                              ?.Replace('ى', 'ي')
                              ?.Replace('ى', 'ي')
                              ?.Replace('ئ', 'ء')
                              ?.Replace("ة", "ه")
                              ?.Replace("`", "")
                              ?.Replace("~", "");
        }

        public static string StripHTML(this string HTMLText, bool decode = true)
        {
            Regex reg = new Regex("<[^>]+>", RegexOptions.IgnoreCase);
            var stripped = reg.Replace(HTMLText, "");
            return decode ? HttpUtility.HtmlDecode(stripped) : stripped;
        }
    }
}
