// <auto-generated />
using System;
using App.Orders.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Modules.Orders.Data.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260922235900_SyncModelSnapshotAfterManualMigrations")]
    partial class SyncModelSnapshotAfterManualMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("App.Shared.Entities.GenericSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Orders_Settings");
                });

            modelBuilder.Entity("Modules.Orders.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountingLastError")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AccountingPostedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("AccountingRetryCount")
                        .HasColumnType("int");

                    b.Property<int>("AccountingStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("ActualCashCollected")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<decimal>("CaptainEarning")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("DeliveryLat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("DeliveryLng")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DeliveryLocationUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("DeliveryOtp")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime?>("DeliveryOtpExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryOtpFailedAttempts")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryUser")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("MoneySnapshotJson")
                        .HasColumnType("longtext");

                    b.Property<int>("MoneySnapshotVersion")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("PaymentDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("longtext");

                    b.Property<string>("ProofOfDeliveryPhotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ProofOfDeliverySignature")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ProofPhotoUploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ProofPhotoUploadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AccountingStatus");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("Orders_Orders");
                });

            modelBuilder.Entity("Modules.Orders.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionRatePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlatformOwnedSnapshot")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("MerchantTitle")
                        .HasColumnType("longtext");

                    b.Property<int>("OrderDetailStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImage")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductUnit")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SingleAdditionalProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SingleFinalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SingleMerchantProfit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SinglePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Warning")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Orders_OrderDetails");
                });

            modelBuilder.Entity("Modules.Orders.Entities.OrderStatusChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("char(36)");

                    b.Property<int>("OrderDetailStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("OrdreDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Orders_OrderStatusChangeLogs");
                });

            modelBuilder.Entity("Modules.Orders.Entities.OrderDetail", b =>
                {
                    b.HasOne("Modules.Orders.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Modules.Orders.Entities.OrderStatusChangeLog", b =>
                {
                    b.HasOne("Modules.Orders.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Modules.Orders.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
