<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="6.0.0" />
    <PackageReference Include="URF.Core.Services" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\App.Services\App.Shared.Services.csproj" />
    <ProjectReference Include="..\Modules.Shipping.Data\Modules.Shipping.Data.csproj" />
    <ProjectReference Include="..\Modules.Shipping.Entities\Modules.Shipping.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Solf">
      <HintPath>..\..\..\Solf\Solf.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
