//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Shared.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Shared.Entities.Resources._Content", typeof(_Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already subscribed to this course.
        /// </summary>
        public static string AlreadySubscribedToThisCourse {
            get {
                return ResourceManager.GetString("AlreadySubscribedToThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Photo (610*1920).
        /// </summary>
        public static string BgPhoto {
            get {
                return ResourceManager.GetString("BgPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarked.
        /// </summary>
        public static string Bookmarked {
            get {
                return ResourceManager.GetString("Bookmarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Style.
        /// </summary>
        public static string ButtonCss {
            get {
                return ResourceManager.GetString("ButtonCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button Url.
        /// </summary>
        public static string ButtonUrl {
            get {
                return ResourceManager.GetString("ButtonUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapter.
        /// </summary>
        public static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string Chapters {
            get {
                return ResourceManager.GetString("Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee.
        /// </summary>
        public static string Committee {
            get {
                return ResourceManager.GetString("Committee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ContentCategory {
            get {
                return ResourceManager.GetString("ContentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content List.
        /// </summary>
        public static string ContentList {
            get {
                return ResourceManager.GetString("ContentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content will be added soon.
        /// </summary>
        public static string ContentWillBeAddedSoon {
            get {
                return ResourceManager.GetString("ContentWillBeAddedSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue from:.
        /// </summary>
        public static string ContinueFrom {
            get {
                return ResourceManager.GetString("ContinueFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons Count.
        /// </summary>
        public static string CouponsCount {
            get {
                return ResourceManager.GetString("CouponsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You finished the course, you can take the quiz from here:.
        /// </summary>
        public static string CourseFinishedTakeQuiz {
            get {
                return ResourceManager.GetString("CourseFinishedTakeQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Info.
        /// </summary>
        public static string CourseInfo {
            get {
                return ResourceManager.GetString("CourseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of courses.
        /// </summary>
        public static string CoursesCount {
            get {
                return ResourceManager.GetString("CoursesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of Customers.
        /// </summary>
        public static string CustomersCount {
            get {
                return ResourceManager.GetString("CustomersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of course questions.
        /// </summary>
        public static string EndOfCourseQuestionCount {
            get {
                return ResourceManager.GetString("EndOfCourseQuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of unit questions.
        /// </summary>
        public static string EndOfUnitQuestionCount {
            get {
                return ResourceManager.GetString("EndOfUnitQuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Image.
        /// </summary>
        public static string FeaturedImage {
            get {
                return ResourceManager.GetString("FeaturedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Image.
        /// </summary>
        public static string HeaderImage {
            get {
                return ResourceManager.GetString("HeaderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string IsBonus {
            get {
                return ResourceManager.GetString("IsBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string IsFree {
            get {
                return ResourceManager.GetString("IsFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed.
        /// </summary>
        public static string IsSubscribed {
            get {
                return ResourceManager.GetString("IsSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Course Includes.
        /// </summary>
        public static string ItemsIncluded {
            get {
                return ResourceManager.GetString("ItemsIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Course.
        /// </summary>
        public static string JoinCourse {
            get {
                return ResourceManager.GetString("JoinCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last lesson.
        /// </summary>
        public static string LastLessonId {
            get {
                return ResourceManager.GetString("LastLessonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson.
        /// </summary>
        public static string Lesson {
            get {
                return ResourceManager.GetString("Lesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessons.
        /// </summary>
        public static string Lessons {
            get {
                return ResourceManager.GetString("Lessons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of lessons.
        /// </summary>
        public static string LessonsCount {
            get {
                return ResourceManager.GetString("LessonsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Lessons.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Start.
        /// </summary>
        public static string LoginToStart {
            get {
                return ResourceManager.GetString("LoginToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Header Image.
        /// </summary>
        public static string MobileHeaderImage {
            get {
                return ResourceManager.GetString("MobileHeaderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to comment!.
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More content is comming soon.
        /// </summary>
        public static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners Images.
        /// </summary>
        public static string PartnersImages {
            get {
                return ResourceManager.GetString("PartnersImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo (Mobile).
        /// </summary>
        public static string PhotoMobile {
            get {
                return ResourceManager.GetString("PhotoMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string Poll {
            get {
                return ResourceManager.GetString("Poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course requirements.
        /// </summary>
        public static string PrerequisiteCourse {
            get {
                return ResourceManager.GetString("PrerequisiteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressPercent {
            get {
                return ResourceManager.GetString("ProgressPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of questions.
        /// </summary>
        public static string QuestionsCount {
            get {
                return ResourceManager.GetString("QuestionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz duration (mins).
        /// </summary>
        public static string QuizDuration {
            get {
                return ResourceManager.GetString("QuizDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Questions.
        /// </summary>
        public static string QuizQuestions {
            get {
                return ResourceManager.GetString("QuizQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register to start.
        /// </summary>
        public static string RegisterToStart {
            get {
                return ResourceManager.GetString("RegisterToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requierments.
        /// </summary>
        public static string Requierments {
            get {
                return ResourceManager.GetString("Requierments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this course.
        /// </summary>
        public static string ShareThisCourse {
            get {
                return ResourceManager.GetString("ShareThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Description Style.
        /// </summary>
        public static string ShortDescriptionCss {
            get {
                return ResourceManager.GetString("ShortDescriptionCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Result.
        /// </summary>
        public static string ShowResult {
            get {
                return ResourceManager.GetString("ShowResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Type.
        /// </summary>
        public static string SlideType {
            get {
                return ResourceManager.GetString("SlideType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name in the link/ slug.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsers Images.
        /// </summary>
        public static string SponsersImages {
            get {
                return ResourceManager.GetString("SponsersImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Now.
        /// </summary>
        public static string StartNow {
            get {
                return ResourceManager.GetString("StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfuly subscribed to this course.
        /// </summary>
        public static string SubscribedToThisCourse {
            get {
                return ResourceManager.GetString("SubscribedToThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Plans.
        /// </summary>
        public static string SubscriptionPlans {
            get {
                return ResourceManager.GetString("SubscriptionPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks For Rating.
        /// </summary>
        public static string ThanksForRating {
            get {
                return ResourceManager.GetString("ThanksForRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Style.
        /// </summary>
        public static string TitleCss {
            get {
                return ResourceManager.GetString("TitleCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Lesson.
        /// </summary>
        public static string ToLesson {
            get {
                return ResourceManager.GetString("ToLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Name.
        /// </summary>
        public static string TrainerName {
            get {
                return ResourceManager.GetString("TrainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer Photo.
        /// </summary>
        public static string TrainerPhoto {
            get {
                return ResourceManager.GetString("TrainerPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Questions.
        /// </summary>
        public static string UnitQuestions {
            get {
                return ResourceManager.GetString("UnitQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of users .
        /// </summary>
        public static string UsersCount {
            get {
                return ResourceManager.GetString("UsersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Thumb.
        /// </summary>
        public static string VideoThumb {
            get {
                return ResourceManager.GetString("VideoThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
    }
}
