//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Shared.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Order {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Order() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Shared.Entities.Resources._Order", typeof(_Order).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App User.
        /// </summary>
        public static string AppUser {
            get {
                return ResourceManager.GetString("AppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        public static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Fixed.
        /// </summary>
        public static string DiscountFixed {
            get {
                return ResourceManager.GetString("DiscountFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percent.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string FailureTitle {
            get {
                return ResourceManager.GetString("FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Price.
        /// </summary>
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Price with Promo Code.
        /// </summary>
        public static string FinalPriceWithPromoCode {
            get {
                return ResourceManager.GetString("FinalPriceWithPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupo Price.
        /// </summary>
        public static string KupoPrice {
            get {
                return ResourceManager.GetString("KupoPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;&lt;img src=&quot;https://onstrategos.com/images/logodark.png&quot; style=&quot;width:350px;&quot;/&gt;&lt;/div&gt;
        ///مرحباً &lt;b&gt;{0}&lt;/b&gt;,&lt;br/&gt;&lt;br/&gt;
        ///&lt;p&gt;يسعدنا تسجيلكم في تخصص التخطيط الإستراتيجي للدولة، برنامج ({1}).&lt;br/&gt;
        ///نود نلفت انتباهكم لما يلي:&lt;/b&gt;.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;بإمكانكم بدء الدراسة الآن، أو في أي وقت تشاؤون.&lt;/li&gt;
        ///&lt;li&gt;لا تتطلب الدراسة الحضور بساعات محددة، وإنما في الأوقات التي تناسبكم.&lt;/li&gt;
        ///&lt;li&gt;كما يسعدنا انضمامكم لمجتمع الدارسين على التلجرام على هذا الرابط: &lt;a href=&quot;https://t.me/joinchat/AN0mKA9HI5xaAyndGr85Ug&quot;&gt;https:/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NewOrderNotificationEmailBody {
            get {
                return ResourceManager.GetString("NewOrderNotificationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أهلا بكم في برنامج التخطيط الاستراتيجي للدولة.
        /// </summary>
        public static string NewOrderNotificationEmailTitle {
            get {
                return ResourceManager.GetString("NewOrderNotificationEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        public static string OrderDetails {
            get {
                return ResourceManager.GetString("OrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Description.
        /// </summary>
        public static string PaymentDescription {
            get {
                return ResourceManager.GetString("PaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        public static string PromoCode {
            get {
                return ResourceManager.GetString("PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qr Code.
        /// </summary>
        public static string QrCode {
            get {
                return ResourceManager.GetString("QrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qr Code Expiry Date.
        /// </summary>
        public static string QrCodeExpiryDate {
            get {
                return ResourceManager.GetString("QrCodeExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Count.
        /// </summary>
        public static string RemainingCount {
            get {
                return ResourceManager.GetString("RemainingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send order completed email.
        /// </summary>
        public static string SendOrderCompletedEmail {
            get {
                return ResourceManager.GetString("SendOrderCompletedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Count.
        /// </summary>
        public static string UsedCount {
            get {
                return ResourceManager.GetString("UsedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
