import { ApplicationRef } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { RouterTestingModule } from '@angular/router/testing';
import { TranslateModule } from '@ngx-translate/core';
import { NgbActiveModal, NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { ToastrService } from 'ngx-toastr';
import { of, Subject, BehaviorSubject, throwError } from 'rxjs';
import { PaginatorState, SortState } from 'src/app/_metronic/shared/crud-table';
import { UsersModule } from '../../users.module';
import { UsersService } from '../../services/users.service';
import { UsersListComponent } from './users-list.component';
import { EditUserModalComponent } from '../edit-user-modal/edit-user-modal.component';
import { DeleteUserModalComponent } from '../delete-user-modal/delete-user-modal.component';
import { ReviewsModule } from '../../../product-reviews/product-reviews.module';
import { productReviewsService } from '../../../product-reviews/services/product-reviews.service';
import { productReviewsListComponent } from '../../../product-reviews/components/product-reviews-list/product-reviews-list.component';
import { NotificationsModule } from '../../../notifications/notifications.module';
import { NotificationsService } from '../../../notifications/services/notifications.service';
import { NotificationsListComponent } from '../../../notifications/components/notifications-list/notifications-list.component';
import { NotificationsCreateComponent } from '../../../notifications/components/notifications-create/notifications-create.component';
import { MerchantsService } from '../../../merchant/services/merchants.service';
import { BulkConfirmModalComponent } from 'src/app/modules/shared/components/bulk-confirm-modal/bulk-confirm-modal.component';

describe('Users and communication HTTP contracts',()=>{
 it('user role and status persist across paging and sorting with global summary',()=>{
  TestBed.configureTestingModule({imports:[HttpClientTestingModule]});const service=TestBed.inject(UsersService),http=TestBed.inject(HttpTestingController);
  service.setDefaults();service.patchState({filter:{role:3,isActive:false}});
  let req=http.expectOne(r=>r.url.endsWith('/Admin/Users/DataTable'));expect(req.request.params.get('role')).toBe('3');expect(req.request.params.get('isActive')).toBe('false');expect(req.request.body.pageNumber).toBe(1);
  req.flush({items:[],totalRecords:50,summary:{total:50,active:0,staff:50,customers:0}});expect(service.summary$.value.total).toBe(50);
  service.paginator.page=1;service.patchState({paginator:service.paginator});req=http.expectOne(r=>r.url.endsWith('/Admin/Users/DataTable'));expect(req.request.params.get('role')).toBe('3');expect(req.request.params.get('isActive')).toBe('false');expect(req.request.body.pageNumber).toBe(2);req.flush({items:[],totalRecords:50});http.verify();service.ngOnDestroy();
 });
 it('review filter reaches API and resets pagination',()=>{
  TestBed.configureTestingModule({imports:[HttpClientTestingModule]});const service=TestBed.inject(productReviewsService),http=TestBed.inject(HttpTestingController);service.setDefaults();service.paginator.page=5;service.patchState({filter:{ratingFilter:'critical'}});
  const req=http.expectOne(r=>r.url.endsWith('/Admin/MerchantReviews/DataTable'));expect(req.request.params.get('ratingFilter')).toBe('critical');expect(req.request.body.pageNumber).toBe(1);req.flush({items:[],totalRecords:12,summary:{total:12,criticalCount:12}});expect(service.summary$.value.criticalCount).toBe(12);http.verify();service.ngOnDestroy();
 });
});
describe('Users communication actual pages and modals',()=>{
 let users:any,reviews:any,notifications:any,modal:any,toast:any;
 const driver:any={id:'driver',firstName:'Reham',lastName:'Mando',fullName:'Reham Mando',phoneNumber:'+963940722840',countryPhoneCode:'+963',isActive:true,role:3,lang:'ar',maxCashFloat:10000,captainCompensationType:2,captainRate:40};
 function table(name:string,methods:string[]){const value=jasmine.createSpyObj(name,['setDefaults','fetchPost','patchState',...methods]);Object.assign(value,{items$:of([]),summary$:new BehaviorSubject<any>(null),totalRecords$:of(100),isLoading$:of(false),listError$:of(''),paginator:new PaginatorState(),sorting:new SortState('id')});for(const method of methods)value[method].and.returnValue(new Subject());return value;}
 beforeEach(async()=>{
  users=table('users',['create','update','delete','changeUserStatus']);reviews=table('reviews',[]);notifications=table('notifications',['getCampaignAudiences','sendCampaign','deleteCampaigns']);notifications.getCampaignAudiences.and.returnValue(of({customers:50,delivery:4,warehouse:6,pushConfigured:true}));
  modal=jasmine.createSpyObj('modal',['close','dismiss']);toast=jasmine.createSpyObj('toast',['success','warning','error','info']);
  await TestBed.configureTestingModule({imports:[HttpClientTestingModule,RouterTestingModule,TranslateModule.forRoot(),UsersModule,ReviewsModule,NotificationsModule],providers:[{provide:UsersService,useValue:users},{provide:productReviewsService,useValue:reviews},{provide:NotificationsService,useValue:notifications},{provide:MerchantsService,useValue:{getAllMerchants:()=>of([{id:30,title:'Other market',active:true}])}},{provide:NgbActiveModal,useValue:modal},{provide:ToastrService,useValue:toast}]}).compileComponents();
 });
 for(const component of [UsersListComponent,EditUserModalComponent,DeleteUserModalComponent,productReviewsListComponent,NotificationsListComponent,NotificationsCreateComponent,BulkConfirmModalComponent])it(component.name+' renders actual template',()=>{const f=TestBed.createComponent(component as any);f.detectChanges();expect(f.nativeElement.textContent.length).toBeGreaterThan(0);f.destroy();});
 it('server summary covers users outside the visible page',()=>{const f=TestBed.createComponent(UsersListComponent);f.detectChanges();users.summary$.next({total:1200,active:900,customers:1100,staff:100});f.detectChanges();expect(f.componentInstance.kpiTotal).toBe(1200);expect(f.componentInstance.kpiStaff).toBe(100);f.destroy();});
 it('role and status filters are combined',()=>{const f=TestBed.createComponent(UsersListComponent);f.detectChanges();f.componentInstance.filterByRole(3);f.componentInstance.filterByStatus('disabled');expect(users.patchState.calls.mostRecent().args[0].filter).toEqual({role:3,isActive:false});f.destroy();});
 it('percentage forty is saved once and API failure stays visible in editor',()=>{const f=TestBed.createComponent(EditUserModalComponent);f.componentInstance.item={...driver};f.detectChanges();const c=f.componentInstance;expect(c.formGroup.valid).toBeTrue();c.save();c.save();expect(users.update).toHaveBeenCalledTimes(1);expect(users.update.calls.mostRecent().args[0].captainRate).toBe(40);users.update.calls.mostRecent().returnValue.error({error:{errorDescription:'تعذر حفظ الحساب'}});f.detectChanges();expect(c.isSaving).toBeFalse();expect(c.saveError).toContain('تعذر');expect(modal.close).not.toHaveBeenCalled();expect(c.formGroup.enabled).toBeTrue();f.destroy();});
 for(const rate of [101,-1,1.005,Infinity])it('invalid compensation '+rate+' is blocked before HTTP',()=>{const f=TestBed.createComponent(EditUserModalComponent);f.componentInstance.item={...driver};f.detectChanges();f.componentInstance.formGroup.patchValue({captainRate:rate});f.componentInstance.save();expect(users.update).not.toHaveBeenCalled();expect(f.componentInstance.formGroup.invalid).toBeTrue();f.destroy();});
 it('new modal cannot reuse the previous modal default user object',()=>{const a=TestBed.createComponent(EditUserModalComponent);a.detectChanges();a.componentInstance.item.firstName='Contaminated';a.destroy();const b=TestBed.createComponent(EditUserModalComponent);b.detectChanges();expect(b.componentInstance.item.firstName).toBe('');b.destroy();});
 it('null legacy phone does not crash editor',()=>{const f=TestBed.createComponent(EditUserModalComponent);f.componentInstance.item={...driver,phoneNumber:null};expect(()=>f.detectChanges()).not.toThrow();expect(f.componentInstance.formGroup.invalid).toBeTrue();f.destroy();});
 it('archiving failure keeps its dialog open with the reason',()=>{const f=TestBed.createComponent(DeleteUserModalComponent);f.componentInstance.id='driver';f.detectChanges();f.componentInstance.delete();f.componentInstance.delete();expect(users.delete).toHaveBeenCalledTimes(1);users.delete.calls.mostRecent().returnValue.error({error:{message:'الحساب لم يُحفظ'}});f.detectChanges();expect(f.componentInstance.errorMessage).toContain('الحساب');expect(modal.dismiss).not.toHaveBeenCalled();expect(modal.close).not.toHaveBeenCalled();f.destroy();});
 it('bulk status reports partial completion and refreshes authoritative list',()=>{users.changeUserStatus.and.callFake((active:boolean,id:string)=>id==='driver'?of(true):throwError(()=>new Error('offline')));const f=TestBed.createComponent(UsersListComponent);f.detectChanges();const records=[{...driver},{...driver,id:'other'}];records.forEach(r=>f.componentInstance.selection.toggle(r,true));f.componentInstance.bulkSetStatus(records,false);expect(toast.error).toHaveBeenCalled();expect(toast.success).not.toHaveBeenCalled();expect(users.fetchPost).toHaveBeenCalledTimes(2);expect(f.componentInstance.isMutating).toBeFalse();f.destroy();});
 it('review statistics are global and an empty summary does not invent five stars',()=>{const f=TestBed.createComponent(productReviewsListComponent);f.detectChanges();expect(f.componentInstance.kpiAvgRating).toBe(0);reviews.summary$.next({total:200,averageRating:3.1,fiveStarCount:90,fiveStarPct:45,criticalCount:20});f.detectChanges();expect(f.componentInstance.kpiTotal).toBe(200);expect(f.componentInstance.kpiAvgRating).toBe(3.1);expect(f.nativeElement.textContent).not.toContain('مرفق صور');f.componentInstance.filterByRating('critical');expect(reviews.patchState).toHaveBeenCalledWith({filter:{ratingFilter:'critical'}});reviews.summary$.next(null);expect(f.componentInstance.kpiTotal).toBe(0);f.destroy();});
 it('review details and photo zoom render their actual nested modal templates',()=>{reviews.items$=of([{id:1,orderId:7,reviewerName:'عم علي محمد',reviewerId:'customer',merchantTitle:'متجر',rate:5,textReview:'ممتاز',createdDate:'2026-10-04T12:00:00',imageReview:'qa'}]);const f=TestBed.createComponent(productReviewsListComponent);f.detectChanges();f.nativeElement.querySelector('.btn-action-view').click();f.detectChanges();TestBed.inject(ApplicationRef).tick();expect(document.body.querySelector('.review-details-modal')?.textContent).toContain('علي محمد');expect(document.body.querySelector('.review-details-modal')?.textContent).not.toContain('عم علي محمد');const photo=document.body.querySelector('.review-details-modal .photo-card') as HTMLElement;photo.click();f.detectChanges();TestBed.inject(ApplicationRef).tick();expect(document.body.querySelector('.review-photo-modal')).not.toBeNull();TestBed.inject(NgbModal).dismissAll();f.destroy();});
 it('copying numeric order number uses text safely',async()=>{const f=TestBed.createComponent(productReviewsListComponent);f.detectChanges();spyOn(navigator.clipboard,'writeText').and.returnValue(Promise.resolve());await f.componentInstance.copyText(7,'رقم الطلب');expect(navigator.clipboard.writeText).toHaveBeenCalledWith('7');expect(toast.info).toHaveBeenCalled();f.destroy();});
 it('clipboard failure shows an error without an unhandled rejection',async()=>{const f=TestBed.createComponent(productReviewsListComponent);f.detectChanges();spyOn(navigator.clipboard,'writeText').and.returnValue(Promise.reject(new Error('Denied')));await f.componentInstance.copyText('ملاحظة');expect(toast.error).toHaveBeenCalled();f.destroy();});
 it('notification list shows total across pages',()=>{const f=TestBed.createComponent(NotificationsListComponent);f.detectChanges();expect(f.componentInstance.totalRecords).toBe(100);f.destroy();});
 it('campaign form locks while sending, prevents duplicate sends, and recovers on error',()=>{const f=TestBed.createComponent(NotificationsCreateComponent);f.detectChanges();const c=f.componentInstance;c.formGroup.patchValue({titleAr:'رسالة مهمة',textAr:'نص إشعار صالح للاختبار'});c.reviewSend();c.send();c.send();c.selectTarget('delivery');expect(notifications.sendCampaign).toHaveBeenCalledTimes(1);expect(c.selectedTarget).toBe('customers');expect(c.formGroup.disabled).toBeTrue();notifications.sendCampaign.calls.mostRecent().returnValue.error({error:{errorDescription:'الخدمة غير متاحة'}});f.detectChanges();expect(c.isSending).toBeFalse();expect(c.formGroup.enabled).toBeTrue();expect(c.sendError).toContain('الخدمة');expect(modal.close).not.toHaveBeenCalled();f.destroy();});
 it('campaign target change clears an incompatible store destination',()=>{const f=TestBed.createComponent(NotificationsCreateComponent);f.detectChanges();const c=f.componentInstance;c.formGroup.patchValue({destination:'merchant',destinationId:30});c.updateDestination();c.selectTarget('delivery');expect(c.formGroup.value.destination).toBe('home');expect(c.formGroup.value.destinationId).toBeNull();expect(c.destinations.some(d=>d.value==='merchant')).toBeFalse();f.destroy();});
 it('sending modal rejects dismissal until request completes',()=>{const ref:any={componentInstance:{isSending:true},result:Promise.resolve()};const ngb=TestBed.inject(NgbModal);spyOn(ngb,'open').and.returnValue(ref);const f=TestBed.createComponent(NotificationsListComponent);f.detectChanges();f.componentInstance.create();const options:any=(ngb.open as jasmine.Spy).calls.mostRecent().args[1];expect(options.beforeDismiss()).toBeFalse();ref.componentInstance.isSending=false;expect(options.beforeDismiss()).toBeTrue();f.destroy();});
 it('bulk failure displays the server partial completion message and disables close during request',()=>{const f=TestBed.createComponent(BulkConfirmModalComponent);const pending=new Subject();f.componentInstance.action=()=>pending;f.detectChanges();f.componentInstance.confirm();f.detectChanges();expect(f.nativeElement.querySelector('.btn-close').disabled).toBeTrue();pending.error({error:{message:'تمت أرشفة 1 من 2 حساب'}});f.detectChanges();expect(f.nativeElement.textContent).toContain('تمت أرشفة 1 من 2');expect(modal.close).not.toHaveBeenCalled();f.destroy();});
});
