//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("app.Services.Resources._Account", typeof(_Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear &lt;b&gt;{0}&lt;/b&gt;,&lt;br/&gt;&lt;br/&gt;
        ///Please click the following link to confirm your email address 
        ///&lt;a href=&apos;{1}&apos;&gt;confirm your email!&lt;/a&gt;
        ///&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;Thank you
        ///&lt;br/&gt;SOL Website.
        /// </summary>
        public static string Email_EmailConfirmationBody {
            get {
                return ResourceManager.GetString("Email_EmailConfirmationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email | SOL Website.
        /// </summary>
        public static string Email_EmailConfirmationSubject {
            get {
                return ResourceManager.GetString("Email_EmailConfirmationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear &lt;b&gt;{0}&lt;/b&gt;,&lt;br/&gt;&lt;br/&gt;
        ///Please click the following link to reset your password
        ///&lt;a href=&apos;{1}&apos;&gt;reset your password!&lt;/a&gt;
        ///&lt;br/&gt;&lt;br/&gt;&lt;br/&gt;Thank you
        ///&lt;br/&gt;SOL Website.
        /// </summary>
        public static string Email_PasswordResetBody {
            get {
                return ResourceManager.GetString("Email_PasswordResetBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password | SOL Website.
        /// </summary>
        public static string Email_PasswordResetSubject {
            get {
                return ResourceManager.GetString("Email_PasswordResetSubject", resourceCulture);
            }
        }
    }
}
