using System.Security.Claims;
using System.Text.Json;
using App.ApiControllers.V1.Admin;
using App.Catalog.Data;
using App.Orders.Data;
using App.Shared.Data.App;
using App.Shared.Data.MultiContext;
using App.Shared.Entities;
using App.Shared.Entities.Enums;
using App.Shared.Entities.Domain;
using App.Shared.Services;
using App.Shared.Services.Options;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Modules.Accounting.Data;
using Modules.Accounting.Entities;
using Modules.Accounting.Services;
using Modules.Catalog.Services;
using Modules.Orders.Entities;
using Moq;
using Solf.Identity;
using Solf.Models;
using AdminUsers = App.ApiControllers.V1.Admin.UsersController;
using AdminNotifications = App.ApiControllers.V1.Admin.NotificationsController;

namespace Modules.Accounting.Tests;
public class UsersCommunicationAuditTests {
 sealed class Fixture:IDisposable {
  readonly SqliteConnection connection=new("Data Source=:memory:");
  public readonly AppDbContext App;
  public readonly OrdersDbContext Orders=new(new DbContextOptionsBuilder<OrdersDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options,null);
  public readonly AccountingDbContext Accounting=new(new DbContextOptionsBuilder<AccountingDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options,null);
  public readonly CatalogDbContext Catalog=new(new DbContextOptionsBuilder<CatalogDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options,null);
  public readonly Mock<UserManager<AppUser>> Users=new(new Mock<IUserStore<AppUser>>().Object,null,null,null,null,null,null,null,null);
  public readonly AppUser User=new(){Id=Guid.NewGuid(),FirstName="Old",LastName="Driver",FullName="Old Driver",UserName="+963940722840",PhoneNumber="+963940722840",CountryPhoneCode="+963",IsActive=true,DefaultLat=34.7m,DefaultLng=36.7m,Birthday=new DateTime(1994,1,1),Lang="tr",CaptainCompensationType=CaptainCompensationType.Percentage,CaptainRate=40m};
  public readonly LedgerService Ledger;
  public Fixture() {
   connection.Open(); App=new(new DbContextOptionsBuilder<AppDbContext>().UseSqlite(connection).Options,null);App.Database.EnsureCreated();
   App.Users.Add(User);
   foreach(var role in new[]{AppRoleName.Customer,AppRoleName.Delivery,AppRoleName.Merchant,AppRoleName.Admin})App.Roles.Add(new(){Id=Guid.NewGuid(),Name=role.ToString(),NormalizedName=role.ToString().ToUpperInvariant()});App.SaveChanges();
   AddRole(User,AppRoleName.Delivery);AddRole(User,AppRoleName.Customer);
   Ledger=new(Accounting,NullLogger<LedgerService>.Instance);
   Users.SetupGet(x=>x.Users).Returns(App.Users);
   Users.Setup(x=>x.FindByIdAsync(It.IsAny<string>())).ReturnsAsync((string id)=>App.Users.SingleOrDefault(u=>u.Id.ToString()==id));
   Users.Setup(x=>x.GetUserAsync(It.IsAny<ClaimsPrincipal>())).ReturnsAsync(User);
   Users.Setup(x=>x.GetRolesAsync(It.IsAny<AppUser>())).ReturnsAsync((AppUser user)=>(IList<string>)App.UserRoles.Where(r=>r.UserId==user.Id).Join(App.Roles,r=>r.RoleId,r=>r.Id,(ur,r)=>r.Name).ToList());
   Users.Setup(x=>x.IsInRoleAsync(It.IsAny<AppUser>(),It.IsAny<string>())).ReturnsAsync((AppUser user,string role)=>App.UserRoles.Any(ur=>ur.UserId==user.Id && App.Roles.Any(r=>r.Id==ur.RoleId && r.Name==role)));
   Users.Setup(x=>x.UpdateAsync(It.IsAny<AppUser>())).Returns(async()=>{await App.SaveChangesAsync();return IdentityResult.Success;});
   Users.Setup(x=>x.AddToRoleAsync(It.IsAny<AppUser>(),It.IsAny<string>())).ReturnsAsync((AppUser user,string role)=>{App.UserRoles.Add(new(){UserId=user.Id,RoleId=App.Roles.Single(r=>r.Name==role).Id});App.SaveChanges();return IdentityResult.Success;});
   Users.Setup(x=>x.RemoveFromRolesAsync(It.IsAny<AppUser>(),It.IsAny<IEnumerable<string>>())).ReturnsAsync((AppUser user,IEnumerable<string> roles)=>{App.UserRoles.RemoveRange(App.UserRoles.Where(ur=>ur.UserId==user.Id && App.Roles.Any(r=>r.Id==ur.RoleId && roles.Contains(r.Name))));App.SaveChanges();return IdentityResult.Success;});
  }
  public void AddRole(AppUser user,AppRoleName role){App.UserRoles.Add(new(){UserId=user.Id,RoleId=App.Roles.Single(r=>r.Name==role.ToString()).Id});App.SaveChanges();}
  public UserDto Request(AppRoleName role=AppRoleName.Delivery)=>new(){FirstName="New",LastName="Driver",PhoneNumber="940722840",CountryPhoneCode="+963",Role=role,IsActive=true,Lang="ar",MaxCashFloat=10000m,CaptainCompensationType=CaptainCompensationType.Percentage,CaptainRate=40m};
  public AdminUsers Controller(IAdminAuditService audit=null,INotificationService notifications=null)=>new(Users.Object,null,null,new AppUnitOfWork(App),null,null,NullLogger<AdminUsers>.Instance,null,null,null,audit,notifications,Accounting,Orders,Catalog,Ledger);
  public NotificationService Notifications() {
   var repo=new Mock<INotificationMessageRepo>();repo.Setup(r=>r.Queryable()).Returns(App.Set<NotificationMessage>());
   repo.Setup(r=>r.Update(It.IsAny<NotificationMessage>())).Callback<NotificationMessage>(n=>App.Update(n));
   return new(new TrackableRepository<Notification,AppDbContext>(App),repo.Object,Options.Create(new SolAppOptions{DefaultLanguage="ar",SupportedLanguages=new[]{"ar"}}),Options.Create(new NotificationOptions{UserTopicSalt="qa"}),null,Users.Object,new AppUnitOfWork(App),null,NullLogger<NotificationService>.Instance);
  }
  public void Dispose(){App.Dispose();connection.Dispose();Accounting.Dispose();Orders.Dispose();Catalog.Dispose();}
 }
 static JsonElement Json(object value)=>JsonSerializer.SerializeToElement(value,new JsonSerializerOptions{PropertyNamingPolicy=JsonNamingPolicy.CamelCase});
 [Theory][InlineData(-1)][InlineData(100.01)][InlineData(1.005)][InlineData(1000000001)]
 public void InvalidCompensationIsRejected(decimal rate){var request=new UserDto{FirstName="First",LastName="Last",PhoneNumber="940722840",Role=AppRoleName.Delivery,CaptainCompensationType=CaptainCompensationType.Percentage,CaptainRate=rate};Assert.NotNull(AdminUsers.ValidateUserInput(request,false));}
 [Theory][InlineData(AppRoleName.Customer)][InlineData(AppRoleName.Merchant)][InlineData(AppRoleName.Delivery)]
 public void EveryNewAccountRequiresPassword(AppRoleName role){var request=new UserDto{FirstName="First",LastName="Last",PhoneNumber="940722840",Role=role};Assert.NotNull(AdminUsers.ValidateUserInput(request,true));request.Password="abcdef";Assert.Null(AdminUsers.ValidateUserInput(request,true));}
 [Fact]public void OperationalFormCannotCreateAdmin(){Assert.NotNull(AdminUsers.ValidateUserInput(new(){FirstName="A",LastName="B",PhoneNumber="9",Role=AppRoleName.Admin,Password="abcdef"},true));}
 [Fact]public async Task ProfileEditPreservesCoordinatesBirthdayAndCustomerRole(){using var f=new Fixture();var birthday=f.User.Birthday;var result=await f.Controller().Edit(f.User.Id,f.Request());Assert.Equal(f.User.Id,result.Value);Assert.Equal(34.7m,f.User.DefaultLat);Assert.Equal(36.7m,f.User.DefaultLng);Assert.Equal(birthday,f.User.Birthday);Assert.Equal("ar",f.User.Lang);Assert.Equal(40m,f.User.CaptainRate);Assert.Equal(2,(await f.Users.Object.GetRolesAsync(f.User)).Count);f.Users.Verify(u=>u.RemoveFromRolesAsync(It.IsAny<AppUser>(),It.IsAny<IEnumerable<string>>()),Times.Never);}
 [Fact]public async Task PartialPayloadCannotExceedExistingPercentage(){using var f=new Fixture();var request=f.Request();request.CaptainCompensationType=null;request.CaptainRate=101m;Assert.IsType<BadRequestObjectResult>((await f.Controller().Edit(f.User.Id,request)).Result);Assert.Equal(40m,f.User.CaptainRate);}
 [Theory][InlineData("cash")][InlineData("earnings")][InlineData("reservation")][InlineData("order")][InlineData("errand")]
 public async Task DriverRoleCannotChangeWhileFinancialOrDeliveryObligationsRemain(string scenario){
  using var f=new Fixture();
  if(scenario=="cash" || scenario=="earnings") {var account=await f.Ledger.GetOrCreateUserAccountAsync(f.User.Id,scenario=="cash"?AccountType.Asset:AccountType.Liability,scenario=="cash"?SystemAccountCodes.CaptainCashFloatPrefix:SystemAccountCodes.CaptainEarningsPrefix,"Driver");var offset=await f.Ledger.GetOrCreateSystemAccountAsync("QA", "Opening", scenario=="cash"?AccountType.Equity:AccountType.Expense);await f.Ledger.PostTransactionAsync(new(){IdempotencyKey="seed",Entries=new(){new(){AccountId=account.Id,Debit=scenario=="cash"?1m:0m,Credit=scenario=="earnings"?1m:0m},new(){AccountId=offset.Id,Credit=scenario=="cash"?1m:0m,Debit=scenario=="earnings"?1m:0m}}});}
  if(scenario=="reservation"){f.Accounting.SettlementRequests.Add(new(){Id=Guid.NewGuid(),RequestedByUserId=f.User.Id,Status=SettlementRequestStatus.Pending,RequestNumber="qa",Currency="SYP",Amount=0m});await f.Accounting.SaveChangesAsync();}
  if(scenario=="order"){f.Orders.Orders.Add(new(){Id=1,DeliveryId=f.User.Id,OrderStatus=OrderStatus.Success,OrderDetails=new List<OrderDetail>{new(){OrderDetailStatus=OrderDetailStatus.MerchantAccepted}}});await f.Orders.SaveChangesAsync();}
  if(scenario=="errand"){f.App.SupportMessages.Add(new(){Title="Purchase",ErrandDriverUserId=f.User.Id,ErrandStatus=ErrandStatus.Assigned});await f.App.SaveChangesAsync();}
  Assert.IsType<BadRequestObjectResult>((await f.Controller().Edit(f.User.Id,f.Request(AppRoleName.Customer))).Result);Assert.Contains("Delivery",await f.Users.Object.GetRolesAsync(f.User));Assert.Equal(40m,f.User.CaptainRate);Assert.IsType<BadRequestObjectResult>((await f.Controller().Delete(f.User.Id)).Result);Assert.Null(f.User.DeletionDate);
 }
 [Fact]public async Task MerchantOwnershipPreventsRoleChange(){using var f=new Fixture();f.AddRole(f.User,AppRoleName.Merchant);f.Catalog.Merchants.Add(new(){Id=30,OwnerId=f.User.Id,Title="Store"});await f.Catalog.SaveChangesAsync();Assert.IsType<BadRequestObjectResult>((await f.Controller().Edit(f.User.Id,f.Request(AppRoleName.Customer))).Result);Assert.IsType<BadRequestObjectResult>((await f.Controller().Delete(f.User.Id)).Result);}
 [Fact]public async Task FailedRoleRemovalRollsBackProfileAndAddedRole(){using var f=new Fixture();f.Users.Setup(u=>u.RemoveFromRolesAsync(It.IsAny<AppUser>(),It.IsAny<IEnumerable<string>>())).ReturnsAsync(IdentityResult.Failed(new IdentityError{Description="Role error"}));Assert.IsType<BadRequestObjectResult>((await f.Controller().Edit(f.User.Id,f.Request(AppRoleName.Merchant))).Result);f.App.ChangeTracker.Clear();var user=await f.App.Users.SingleAsync();Assert.Equal("Old Driver",user.FullName);Assert.Equal("tr",user.Lang);Assert.DoesNotContain("Merchant",await f.Users.Object.GetRolesAsync(user));Assert.Contains("Delivery",await f.Users.Object.GetRolesAsync(user));}
 [Fact]public async Task FailedPasswordResetRollsBackProfile(){using var f=new Fixture();f.Users.Setup(u=>u.GeneratePasswordResetTokenAsync(It.IsAny<AppUser>())).ReturnsAsync("token");f.Users.Setup(u=>u.ResetPasswordAsync(It.IsAny<AppUser>(),"token","abcdef")).ReturnsAsync(IdentityResult.Failed(new IdentityError{Description="Password error"}));var request=f.Request();request.Password="abcdef";Assert.IsType<BadRequestObjectResult>((await f.Controller().Edit(f.User.Id,request)).Result);f.App.ChangeTracker.Clear();Assert.Equal("Old Driver",(await f.App.Users.SingleAsync()).FullName);}
 [Fact]public async Task DeletedAccountCannotBeEnabled(){using var f=new Fixture();f.User.DeletionDate=DateTime.UtcNow;await f.App.SaveChangesAsync();Assert.IsType<NotFoundResult>((await f.Controller().Enable(f.User.Id)).Result);}
 [Fact]public async Task FailedIdentityUpdateIsNotReportedAsEnabled(){using var f=new Fixture();f.Users.Setup(u=>u.UpdateAsync(It.IsAny<AppUser>())).ReturnsAsync(IdentityResult.Failed(new IdentityError{Description="Failed"}));Assert.IsType<BadRequestObjectResult>((await f.Controller().Enable(f.User.Id)).Result);}
 [Fact]public async Task AdminAccountCannotBeDisabledEditedOrArchived(){using var f=new Fixture();f.AddRole(f.User,AppRoleName.Admin);Assert.IsType<BadRequestObjectResult>((await f.Controller().Disable(f.User.Id)).Result);Assert.IsType<BadRequestObjectResult>((await f.Controller().Delete(f.User.Id)).Result);Assert.IsType<BadRequestObjectResult>((await f.Controller().Edit(f.User.Id,f.Request())).Result);}
 [Fact]public async Task AuditAndDisablePushFailureDoNotUndoSuccessfulEdit(){using var f=new Fixture();var audit=new Mock<IAdminAuditService>();audit.Setup(a=>a.LogAsync(It.IsAny<AdminAuditLogEntry>())).ThrowsAsync(new Exception("Audit unavailable"));var notifications=new Mock<INotificationService>();notifications.Setup(n=>n.SendPushNotification(It.IsAny<Notification>(),It.IsAny<Guid[]>(),It.IsAny<bool>(),It.IsAny<bool>())).ThrowsAsync(new Exception("Push unavailable"));var request=f.Request();request.IsActive=false;Assert.Equal(f.User.Id,(await f.Controller(audit.Object,notifications.Object).Edit(f.User.Id,request)).Value);Assert.False(f.User.IsActive);}
 [Fact]public async Task UsersSummaryAndFiltersCoverAllPagesAndExcludeDualRoleAdmin(){using var f=new Fixture();for(int i=0;i<4;i++){var u=new AppUser{Id=Guid.NewGuid(),FullName="Customer "+i,IsActive=i<3,Lang="en"};f.App.Users.Add(u);f.App.SaveChanges();f.AddRole(u,AppRoleName.Customer);if(i==2)f.AddRole(u,AppRoleName.Admin);}var c=f.Controller();var data=Json(Assert.IsType<OkObjectResult>((await c.DataTable(new(){PageNumber=1,PageSize=1},AppRoleName.Customer,true)).Result).Value);Assert.Equal(2,data.GetProperty("totalRecords").GetInt32());Assert.Equal(2,data.GetProperty("summary").GetProperty("active").GetInt32());Assert.Equal("en",data.GetProperty("items")[0].GetProperty("lang").GetString());Assert.Equal(1,data.GetProperty("items").GetArrayLength());}
 [Fact]public async Task ReviewPagesFiltersStatisticsAndFullNameSearchStayConsistent(){using var f=new Fixture();f.Orders.MerchantReviews.AddRange(Enumerable.Range(1,4).Select(i=>new MerchantReview{Id=i,OrderId=i,MerchantId=30,ReviewerId=f.User.Id,Rate=i==1?1:5,CreatedDate=DateTime.UtcNow.Date,TextReview=i==1?"Low":null}));await f.Orders.SaveChangesAsync();var merchants=new Mock<IMerchantService>();merchants.Setup(m=>m.Queryable()).Returns(f.Catalog.Merchants);var controller=new MerchantReviewsController(new OrdersUnitOfWork(f.Orders),merchants.Object,new AppUnitOfWork(f.App));var a=Json(Assert.IsType<OkObjectResult>((await controller.DataTable(new(){PageNumber=1,PageSize=1,Search="Old Driver"})).Result).Value);var b=Json(Assert.IsType<OkObjectResult>((await controller.DataTable(new(){PageNumber=2,PageSize=1})).Result).Value);Assert.Equal(4,a.GetProperty("totalRecords").GetInt32());Assert.Equal(4,a.GetProperty("summary").GetProperty("averageRating").GetDouble());Assert.Equal(3,a.GetProperty("summary").GetProperty("fiveStarCount").GetInt32());Assert.NotEqual(a.GetProperty("items")[0].GetProperty("id").GetInt32(),b.GetProperty("items")[0].GetProperty("id").GetInt32());Assert.Equal(f.User.Id,a.GetProperty("items")[0].GetProperty("reviewerId").GetGuid());var critical=Json(Assert.IsType<OkObjectResult>((await controller.DataTable(new(){PageNumber=1},"critical")).Result).Value);Assert.Equal(1,critical.GetProperty("totalRecords").GetInt32());}
 [Fact]public async Task RemovedRoleInvalidatesOldTokenImmediately(){using var f=new Fixture();var context=new DefaultHttpContext{User=new ClaimsPrincipal(new ClaimsIdentity(new[]{new Claim(ClaimTypes.Role,"Merchant")},"test"))};var called=false;await new App.Helpers.DisabledAccountMiddleware(_=>{called=true;return Task.CompletedTask;}).InvokeAsync(context,f.Users.Object);Assert.False(called);Assert.Equal(401,context.Response.StatusCode);}
 [Fact]public async Task CurrentRoleTokenStillWorks(){using var f=new Fixture();var context=new DefaultHttpContext{User=new ClaimsPrincipal(new ClaimsIdentity(new[]{new Claim(ClaimTypes.Role,"Delivery")},"test"))};var called=false;await new App.Helpers.DisabledAccountMiddleware(_=>{called=true;return Task.CompletedTask;}).InvokeAsync(context,f.Users.Object);Assert.True(called);}
 [Fact]public async Task NotificationPagesReadOnlyTheirOwnTwentyRecords(){using var f=new Fixture();var other=Guid.NewGuid();f.App.Users.Add(new(){Id=other,UserName="other",IsActive=true});for(int i=1;i<=25;i++)f.App.Notifications.Add(new(){Id=i,Topic="all",CreatedDate=DateTime.UtcNow.Date,NotificationType=NotificationType.GlobalNotification,NotificationMessages=new List<NotificationMessage>{new(){UserId=f.User.Id},new(){UserId=other}}});await f.App.SaveChangesAsync();var service=f.Notifications();Assert.Equal(20,(await service.GetNotifications(f.User.Id)).Length);Assert.Equal(5,(await service.GetNotifications(f.User.Id,page:1)).Length);Assert.Equal(0,await service.CountUnreadNotifications(f.User.Id));Assert.Equal(25,await service.CountUnreadNotifications(other));Assert.Equal(0,f.App.Notifications.Sum(n=>n.NotLoggedInReadCount));}
 [Fact]public async Task ReadAllAndReceivedDoNotTouchAnotherAccount(){using var f=new Fixture();var other=Guid.NewGuid();f.App.Users.Add(new(){Id=other,UserName="other",IsActive=true});f.App.Notifications.Add(new(){Id=1,Topic="all",NotificationType=NotificationType.GlobalNotification,NotificationMessages=new List<NotificationMessage>{new(){UserId=f.User.Id},new(){UserId=other}}});await f.App.SaveChangesAsync();var service=f.Notifications();await service.MarkAsRecived(f.User.Id,1);Assert.NotNull(f.App.Set<NotificationMessage>().Single(m=>m.UserId==f.User.Id).RecivedDate);Assert.Null(f.App.Set<NotificationMessage>().Single(m=>m.UserId==other).RecivedDate);await service.MarkAsRead(f.User.Id,null);Assert.Equal(0,await service.CountUnreadNotifications(f.User.Id));Assert.Equal(1,await service.CountUnreadNotifications(other));}
 [Fact]public async Task NewDriverDefaultsToSalaryWithoutInventingCommission(){using var f=new Fixture();f.Users.Setup(u=>u.CreateAsync(It.IsAny<AppUser>(),It.IsAny<string>())).ReturnsAsync((AppUser user,string password)=>{user.Id=Guid.NewGuid();f.App.Users.Add(user);f.App.SaveChanges();return IdentityResult.Success;});var request=f.Request();request.FirstName="  New  ";request.LastName="  Name  ";request.PhoneNumber="940722841";request.Password="abcdef";request.CaptainCompensationType=null;request.CaptainRate=40m;var result=await f.Controller().Create(request);Assert.Null(result.Result);var created=f.App.Users.Single(u=>u.Id==result.Value);Assert.Equal("New Name",created.FullName);Assert.Equal(CaptainCompensationType.SalariedEmployee,created.CaptainCompensationType);Assert.Equal(0m,created.CaptainRate);}
 [Fact]public async Task FailedNewRoleDoesNotLeaveAnOrphanAccount(){using var f=new Fixture();f.Users.Setup(u=>u.CreateAsync(It.IsAny<AppUser>(),It.IsAny<string>())).ReturnsAsync((AppUser user,string password)=>{user.Id=Guid.NewGuid();f.App.Users.Add(user);f.App.SaveChanges();return IdentityResult.Success;});f.Users.Setup(u=>u.AddToRoleAsync(It.IsAny<AppUser>(),It.IsAny<string>())).ReturnsAsync(IdentityResult.Failed(new IdentityError{Description="Failed"}));var request=f.Request();request.PhoneNumber="940722841";request.Password="abcdef";Assert.IsType<BadRequestObjectResult>((await f.Controller().Create(request)).Result);f.App.ChangeTracker.Clear();Assert.Single(f.App.Users);}
 [Fact]public async Task ArchivedSettledDriverKeepsHistoryAndRoles(){using var f=new Fixture();Assert.True((await f.Controller().Delete(f.User.Id)).Value);Assert.False(f.User.IsActive);Assert.NotNull(f.User.DeletionDate);Assert.Contains("Delivery",await f.Users.Object.GetRolesAsync(f.User));Assert.Single(f.App.Users);}
 [Fact]public async Task CampaignAuditFailureDoesNotInviteResending(){using var f=new Fixture();var service=new Mock<INotificationService>();service.Setup(x=>x.IsCampaignPushConfigured()).Returns(true);service.Setup(x=>x.SendCampaignNotification(It.IsAny<Notification>(),It.IsAny<Guid[]>())).ReturnsAsync(new CampaignPushResult{AcceptedLanguages=3,RecipientAccounts=1});f.Users.Setup(u=>u.GetUsersInRoleAsync("Customer")).ReturnsAsync(new List<AppUser>{f.User});var audit=new Mock<IAdminAuditService>();audit.Setup(a=>a.LogAsync(It.IsAny<AdminAuditLogEntry>())).ThrowsAsync(new Exception("Logging offline"));var c=new AdminNotifications(service.Object,f.Users.Object,null,audit.Object);var result=await c.Create(new(){Target="customers",TitleAr="رسالة مهمة",TextAr="نص إشعار للاختبار"});Assert.Equal(3,result.Value.AcceptedLanguages);service.Verify(s=>s.SendCampaignNotification(It.IsAny<Notification>(),It.IsAny<Guid[]>()),Times.Once);}
 [Fact]public async Task AnonymousFeedPagesCannotReadStaffCampaigns(){using var f=new Fixture();for(int i=1;i<=26;i++)f.App.Notifications.Add(new(){Id=i,Topic=i==26?"campaign_delivery":"all",CreatedDate=DateTime.UtcNow.Date,NotificationType=NotificationType.GlobalNotification});await f.App.SaveChangesAsync();var service=f.Notifications();Assert.Equal(20,(await service.GetNotifications(null)).Length);Assert.Equal(5,(await service.GetNotifications(null,page:1)).Length);await service.MarkAsRead(null,26);Assert.Equal(0,f.App.Notifications.Single(n=>n.Id==26).NotLoggedInReadCount);}
 [Fact]public void TestPushRequiresAdministrativePermission(){var method=typeof(App.ApiControllers.V1.NotificationsController).GetMethod("Test");Assert.Equal(nameof(AppPermissionKey.AdminPermission),method.GetCustomAttributes(typeof(AuthorizeAttribute),true).Cast<AuthorizeAttribute>().Single().Policy);}
}
