<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="FirebaseAdmin" Version="2.1.0" />
    <PackageReference Include="MaxMind.GeoIP2" Version="4.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="5.0.6" />
    <PackageReference Include="MimeKit" Version="2.11.0" />
    <PackageReference Include="Sendgrid" Version="9.23.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.9" />
    <PackageReference Include="Twilio" Version="5.60.0" />
    <PackageReference Include="URF.Core.All" Version="3.0.0" />
    <PackageReference Include="URF.Core.Services" Version="3.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\app.Entities\app.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AutoMapper">
      <HintPath>..\..\..\..\.nuget\packages\automapper\7.0.1\lib\netcoreapp2.0\AutoMapper.dll</HintPath>
    </Reference>
    <Reference Include="SendGrid">
      <HintPath>..\..\..\..\.nuget\packages\sendgrid\9.10.0\lib\netstandard2.0\SendGrid.dll</HintPath>
    </Reference>
    <Reference Include="Solf">
      <HintPath>..\Solf\Solf.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\_Account.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Account.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\_Performance.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>_Performance.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\_Account.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Account.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Account.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Performance.ar.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\_Performance.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>_Performance.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
